services:
  crawler:
    build: .
    command: python /src/crawler.py
    container_name: crawler
    volumes:
      - ./src/:/src/
      - ./test/:/test/
  test_crawler:
    build: .
    command: python -m unittest discover -s /test/ -p "*_test.py" -v
    container_name: test_crawler
    volumes:
      - ./src/:/src/
      - ./test/:/test/
  log-view:
    image: amir20/dozzle:latest
    container_name: log-view
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    ports: ["9999:8080"]

