name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-20.04
    environment: 
      name: dev
      url: https://github.com/andrepreira/crwaler_desafio_neoway

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.10
        cache: 'pip' # caching pip dependencies

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip freeze

    - name: Run tests
      run: |
        python -m unittest discover -v

#     - name: Store test results
#       uses: actions/upload-artifact@v2
#       with:
#         name: test-results
#         path: test-results
