name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-20.04
    environment: 
      name: dev
      url: https://github.com/andrepreira/crwaler_desafio_neoway

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.10
        cache: 'pip' # caching pip dependencies

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  test:
    runs-on: ubuntu-20.04
    environment: 
      name: dev
      url: https://github.com/andrepreira/crwaler_desafio_neoway
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.10
        cache: 'pip' # caching pip dependencies

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            
    - name: Run tests
      run: |
        python -m unittest discover -v

