name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-20.04
    environment: 
      name: dev
      url: https://dev.example.com

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.10

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt --use-pep517

    - name: Run tests
      run: |
        python -m unittest discover -v

#     - name: Store test results
#       uses: actions/upload-artifact@v2
#       with:
#         name: test-results
#         path: test-results
